#@data/values
---
deliverable:
  #! The only required parameter is the name of the namespace. All additional values provided here
  #! for a namespace will be available under data.values for templating additional sources

apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: spring-music
  labels:
    app.kubernetes.io/part-of: spring-music
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: deliverable
    app.tanzu.vmware.com/deliverable-type: web
    carto.run/cluster-template-name: external-deliverable-template
    carto.run/resource-name: deliverable
    carto.run/supply-chain-name: source-to-url
    carto.run/template-kind: ClusterTemplate
    carto.run/template-lifecycle: mutable
    carto.run/workload-name: spring-music
    carto.run/workload-namespace: default
spec:
  source:
    image: tapautomation.azurecr.io/supply-chain/spring-music-default-bundle:ade4f185-5b40-4152-a25c-53d68357d302
